version: '3.8'
services:
    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './app:/application'
            - './.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '2000:80'

    php-fpm:
        build: .docker/php-fpm
        working_dir: /application
        volumes:
            - './app:/application'
            - './.docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
